version: 2.1
jobs:
  build:
    docker: 
      - image: rust:1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: cargo --version
      - run: cargo build
